apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-game-tab-fe
  namespace: minigame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-game-tab-fe
  template:
    metadata:
      labels:
        app: mini-game-tab-fe
    spec:
      containers:
      - name: mini-game-tab-fe-container
        image: phuc1205/mini-game-tab-fe:v1.0.0
        ports:
        - containerPort: 80