export const ENDPOINTS = {
	auth: '/auth',
	me: '/me',
	harvest: '/harvest',
	upgrades: '/upgrades',
	tap: '/tap',
	boostList: '/boost-list',
	boost: '/boost',
	myTasks: '/my-tasks',
	completeTask: '/complete-task',
	refererList: '/referer-list',
	energyRefill: '/energy-refill',
	infinityTap: '/infinity-tap',
	statistic: '/statistic',
	tapbotClaim: 'tapbot-claim',
	txStatus: '/tran-status',
	getAirdrop: 'get_airdrop_token',
	confirmAirdrop: 'confirm_receive_airdrop_token',
	withdrawRequest: 'withdraw-request',
	listWithdrawRequest: 'list-withdraw-request',
	listUserWithdrawRequest: 'list-user-withdraw-request'
};
